# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 01:38
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(default='photo', max_length=100)),
                ('photo', models.ImageField(default=0, storage=django.core.files.storage.FileSystemStorage(location='/var/www/html/PHOTOS/'), upload_to='')),
                ('azimuth', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('pitch', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('roll', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('alt', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('ppm', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('topLeftX', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('topLeftY', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('topRightX', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('topRightY', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('bottomLeftX', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('bottomLeftY', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('bottomRightX', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('bottomRightY', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_pic', models.ImageField(default=0, storage=django.core.files.storage.FileSystemStorage(location='/var/www/html/TARGETS/'), upload_to='')),
                ('color', models.CharField(max_length=10)),
                ('lcolor', models.CharField(max_length=10)),
                ('orientation', models.CharField(choices=[('N', 'N'), ('NE', 'NE'), ('E', 'E'), ('SE', 'SE'), ('S', 'S'), ('SW', 'SW'), ('W', 'W'), ('NW', 'NW')], max_length=2)),
                ('shape', models.CharField(choices=[('CIR', 'Circle'), ('SCI', 'Semicircle'), ('QCI', 'Quarter Circle'), ('TRI', 'Triangle'), ('SQU', 'Square'), ('REC', 'Rectangle'), ('TRA', 'Trapezoid'), ('PEN', 'Pentagon'), ('HEX', 'Hexagon'), ('HEP', 'Heptagon'), ('OCT', 'Octagon'), ('STA', 'Star'), ('CRO', 'Cross')], max_length=3)),
                ('letter', models.CharField(max_length=1)),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.Picture')),
            ],
        ),
    ]
