# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 00:29
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20151214_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(default=0, storage=django.core.files.storage.FileSystemStorage(location='/var/www/html/PHOTOS/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='target',
            name='orientation',
            field=models.CharField(choices=[('N', 'N'), ('NE', 'NE'), ('E', 'E'), ('SE', 'SE'), ('S', 'S'), ('SW', 'SW'), ('W', 'W'), ('NW', 'NW')], max_length=2),
        ),
        migrations.AlterField(
            model_name='target',
            name='shape',
            field=models.CharField(choices=[('CIR', 'Circle'), ('SCI', 'Semicircle'), ('QCI', 'Quarter Circle'), ('TRI', 'Triangle'), ('SQU', 'Square'), ('REC', 'Rectangle'), ('TRA', 'Trapezoid'), ('PEN', 'Pentagon'), ('HEX', 'Hexagon'), ('HEP', 'Heptagon'), ('OCT', 'Octagon'), ('STA', 'Star'), ('CRO', 'Cross')], max_length=3),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_pic',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/var/www/html/TARGETS/'), upload_to=''),
        ),
    ]
