# Generated by iptables-save v1.4.21 on Fri Dec 25 16:06:01 2015
*filter
:INPUT DROP [407:107385]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [45294:2435948]
-A INPUT -i wlan0 -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -i wlan0 -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -i wlan0 -p tcp -m tcp --dport 53 -j ACCEPT
-A INPUT -i wlan0 -p tcp -m tcp --dport 5353 -j ACCEPT
-A INPUT -i wlan0 -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -i wlan0 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -i wlan0 -p udp -m udp --dport 5353 -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m tcp --dport 2000 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 6379 -j ACCEPT
-A INPUT -p udp -m udp --dport 6379 -j ACCEPT
-A INPUT -p udp -m udp --dport 2000 -j ACCEPT
COMMIT
# Completed on Fri Dec 25 16:06:01 2015
